# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ealmr
email:
description: > # this means to ignore newlines until "baseurl:"
  personal blog
baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://ealmr.pw" # the base hostname & protocol for your site
permalink: /:title
timezone: Asia/Shanghai
twitter_username: 
github_username: 
google_analytics: UA-76951800-1

plugins:
  - jekyll-paginate
  - jekyll-asciidoc
  - jekyll-sitemap

paginate: 20
paginate_path: "page:num"
highlighter: rouge
# Build settings
markdown: Kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge

sass:
    sass_dir: ./_sass
#    style: :compressed

asciidoctor:
  attributes:
    - icons=font
    - hardbreaks!
    - source-highlighter=coderay

#compress_html:
#    clippings: all
#    ignore:
#        envs: ["test"]

exclude: ['README.adoc', 'Gemfile.lock', 'Gemfile', '*.sh']
